name: IPFS Setup Action
description: A GitHub Action to install and initialize IPFS
author: Sawood Alam <@ibnesayeed>
inputs:
  ipfs_version:
    description: An exact IPFS version of a released binary (https://dist.ipfs.io/go-ipfs/versions)
    default: 0.5
runs:
  using: node12
  main: dist/index.js
branding:
  icon: package  
  color: blue
